name: socket_logging
description: cross-platform web socket logging solution
version: 1.0.0+1
homepage: https://github.com/FMotalleb

environment:
  sdk: ">=2.18.6 <3.0.0"
executables:
  log_server: "server_example.dart"

dev_dependencies:
  lints: ^2.0.0
  http: ^0.13.5
  test: ^1.16.0
dependencies:
  logging: ^1.1.0
